version: '3.8'

services:
  db:
    image: postgres:15
    container_name: vitrina-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vitrina123
      POSTGRES_DB: vitrina
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: vitrina-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  pgdata:
